name: Terraform CI/CD Pipeline

on:
  push:
    branches:
      - main
      
jobs:
  terraform:
    runs-on: ubuntu-latest

    steps:
      # Checkout code from the repository
      - name: Checkout code
        uses: actions/checkout@v2

      # Set up AWS credentials using OIDC (no need for hardcoded secrets)
      - name: Configure AWS credentials
        id: aws-creds
        uses: aws-actions/configure-aws-credentials@v3
        with:
         role-to-assume: arn:aws:iam::354918400547:role/TF_role_github
         aws-region: us-east-1

      # Install Terraform
      - name: Install Terraform
        uses: hashicorp/setup-terraform@v1
        with:
          terraform_version: 1.5.3  # Specify the version of Terraform you want to use

      # Initialize Terraform
      - name: Terraform Init
        run: terraform init -backend-config=backend.tf

      # Validate Terraform configuration
      - name: Terraform Validate
        run: terraform validate

      # Run Terraform Plan to check what will be created/modified
      - name: Terraform Plan
        run: terraform plan -var-file=configs/dev.tfvars

      # Apply Terraform Plan to provision infrastructure
      - name: Terraform Apply
        run: terraform apply -auto-approve -var-file=configs/dev.tfvars

      # Output terraform state (optional, but can be helpful for debugging)
      - name: Terraform Output
        run: terraform output

      - name: Terraform Destroy
        run: terraform destroy -auto-approve -var-file=configs/dev.tfvars
