name: Terraform Deployment

on:
  push:
    branches:
      - main
  workflow_dispatch:
    inputs:
      apply_approval:
        description: 'Do you want to proceed with Terraform Apply? (yes/no)'
        required: true
        type: choice
        options:
          - yes
          - no
      destroy_approval:
        description: 'Do you want to proceed with Terraform Destroy? (yes/no)'
        required: true
        type: choice
        options:
          - yes
          - no

permissions:
  id-token: write  # Allows OIDC token usage
  contents: read   # Allows reading the repo content

jobs:
  terraform:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v3
        with:
          role-to-assume: arn:aws:iam::354918400547:role/Github-tf-role
          aws-region: us-east-1
          audience: sts.amazonaws.com

      - name: Install Terraform
        uses: hashicorp/setup-terraform@v1
        with:
          terraform_version: 1.5.3  

      - name: Terraform Init
        run: terraform init

      - name: Terraform Plan
        run: terraform plan -var-file=configs/dev.tfvars

      - name: Terraform Apply (Manual Approval)
        if: ${{ github.event.inputs.apply_approval == 'yes' }}
        run: terraform apply -var-file=configs/dev.tfvars -auto-approve

      - name: Terraform Destroy (Manual Approval)
        if: ${{ github.event.inputs.destroy_approval == 'yes' }}
        run: terraform destroy -var-file=configs/dev.tfvars -auto-approve
